sql_name = "postgres"
sql_password = "habitat1"
sql_dbname = "postgres"
sql_host = "localhost"
sql_graph = "graph_model"
sql_provenance = "nb_provenance"
sql_dbs = "rowstore"

neo_name = "neo4j"
neo_password = "habitat1"
neo_host = "localhost:7474"
neo_db = "data"
